=== MennoCoehoorn/WebPub2021/Zadania/1.1/spotify.dtd
<!-- Root Element -->
<!ELEMENT spotify (music, other_content)>
<!ATTLIST spotify language CDATA #FIXED "EN">

<!-- Depth 1 -->
<!ELEMENT music (genres, artists)>
<!ELEMENT other_content (podcast_genres, podcasts)>

<!-- Depth 2 -->

<!-- music -->
<!ELEMENT genres (genre+)>
<!ELEMENT artists (artist+)>

<!-- other_content -->
<!ELEMENT podcast_genres (podcast_genre+)>
<!ELEMENT podcasts (podcast+)>

<!-- Depth 3 -->

<!-- genres -->
<!ELEMENT genre (name,subgenres+)>

<!-- artists -->
<!ELEMENT artist (name, career_start, followers, album_count, albums)>

<!-- podcast_genres -->
<!ELEMENT podcast_genre (name, subgenres+)>

<!-- podcasts -->
<!ELEMENT podcast (name, language, author, first_date, ep_count, release_window, description, episodes)>

<!-- Depth 4 -->

<!-- genres + podcast_genre -->
<!ELEMENT subgenres (subgenre+)>

<!-- artist -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT career_start (#PCDATA)>
<!ELEMENT followers (#PCDATA)>
<!ELEMENT album_count (#PCDATA)>
<!ELEMENT albums (album+)>

<!-- podcast -->
<!ELEMENT language (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT first_date (#PCDATA)>
<!ELEMENT ep_count (#PCDATA)>
<!ELEMENT release_window (day, hour, periodicity)>
<!ELEMENT description ANY>
<!ELEMENT episodes (episode+)>
<!ATTLIST podcast subgenre_ID CDATA #REQUIRED>

<!-- Depth 5 -->

<!-- subgenres -->
<!ELEMENT subgenre (name, count)>

<!-- albums -->
<!ELEMENT album (name, release_date, track_count, songs+)>

<!-- release_window -->
<!ELEMENT day (#PCDATA)>
<!ELEMENT hour (#PCDATA)>
<!ELEMENT periodicity (#PCDATA)>

<!-- episodes -->
<!ELEMENT episode (name, episode_num, release_date, length, description, guests?)>

<!-- Depth 6 -->

<!-- subgenre -->
<!ATTLIST subgenre subgenre_ID ID #REQUIRED>
<!ELEMENT count (#PCDATA)>

<!-- album -->
<!ELEMENT release_date (#PCDATA)>
<!ELEMENT track_count (#PCDATA)>
<!ELEMENT songs (song+)>
<!ATTLIST album subgenre_ID CDATA #REQUIRED>
<!ATTLIST album rating (0|1|2|3|4|5) "0">

<!-- episode -->
<!ELEMENT episode_num (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT guests (guest+)>
<!ATTLIST episode rating (0|1|2|3|4|5) "0">

<!-- Depth 7 -->

<!-- songs -->
<!ELEMENT song (track_num, name, length, featurings?)>

<!-- guests -->
<!ELEMENT guest (#PCDATA)>

<!-- Depth 8 -->

<!-- song -->
<!ELEMENT track_num (#PCDATA)>
<!ELEMENT featurings (featuring+)>
<!ATTLIST song rating (0|1|2|3|4|5) "0">

<!-- Depth 9 -->

<!-- featurings -->
<!ELEMENT featuring (#PCDATA)>

=== MennoCoehoorn/WebPub2021/Zadania/1.1/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spotify SYSTEM "spotify.dtd">
<spotify language="EN">
    
    <music>
        
        <genres>
            
            <genre>
                <name>Rock</name>

                <subgenres>
                    <subgenre subgenre_ID="m_1">
                        <name>Alternative Rock</name>
                        <count>2</count>
                    </subgenre>
                    <subgenre subgenre_ID="m_2">
                        <name>Pop Rock</name>
                        <count>1</count>
                    </subgenre>
                </subgenres>

            </genre>

            <genre>
                
                <name>Pop</name>

                <subgenres>
                    <subgenre subgenre_ID="m_3">
                        <name>K-Pop</name>
                        <count>3</count>
                    </subgenre>
                </subgenres>

            </genre>
        </genres>

        <artists>
            
            <artist>
                <name>Red Hot Chili Peppers</name>
                <career_start>1983</career_start>
                <followers>15 850 624</followers>
                <album_count>2</album_count>
                <albums>

                    <album subgenre_ID="m_1" rating="5">
                        
                        <name>Californication</name>
                        <release_date>8-6-1999</release_date>
                        <track_count>15</track_count>

                        <songs>

                            <song rating="3">
                                <track_num>1</track_num>
                                <name>Around the World</name>
                                <length>3:59</length>
                            </song>

                            <song rating="3">
                                <track_num>2</track_num>
                                <name>Parallel Universe</name>
                                <length>4:29</length>
                            </song>

                            <song rating="5">
                                <track_num>3</track_num>
                                <name>Scar Tissue</name>
                                <length>3:36</length>
                            </song>

                            <song rating="5">
                                <track_num>4</track_num>
                                <name>Otherside</name>
                                <length>4:15</length>
                            </song>

                            <song rating="2">
                                <track_num>5</track_num>
                                <name>Get on Top</name>
                                <length>3:18</length>
                            </song>

                            <song rating="5">
                                <track_num>6</track_num>
                                <name>Californication</name>
                                <length>5:30</length>
                            </song>

                            <song rating="2">
                                <track_num>7</track_num>
                                <name>Easily</name>
                                <length>3:51</length>
                            </song>

                            <song rating="3">
                                <track_num>8</track_num>
                                <name>Porcelain</name>
                                <length>2:44</length>
                            </song>

                            <song rating="3">
                                <track_num>9</track_num>
                                <name>Emit Remmus</name>
                                <length>4:00</length>
                            </song>

                            <song rating="4">
                                <track_num>10</track_num>
                                <name>I Like Dirt</name>
                                <length>2:38</length>
                            </song>

                            <song rating="4">
                                <track_num>11</track_num>
                                <name>This Velvet Glove</name>
                                <length>3:45</length>
                            </song>

                            <song rating="3">
                                <track_num>12</track_num>
                                <name>Savior</name>
                                <length>4:52</length>
                            </song>

                            <song rating="4">
                                <track_num>13</track_num>
                                <name>Purple Stain</name>
                                <length>4:13</length>
                            </song>

                            <song rating="2">
                                <track_num>14</track_num>
                                <name>Right on Time</name>
                                <length>1:53</length>
                            </song>

                            <song rating="5">
                                <track_num>15</track_num>
                                <name>Road Trippin'</name>
                                <length>3:25</length>
                            </song>

                        </songs>

                    </album>

                    <album subgenre_ID="m_1" rating="4">
                        
                        <name>The Getaway</name>
                        <release_date>17-6-2016</release_date>
                        <track_count>5</track_count>

                        <songs>
                            <song rating="5">
                                <track_num>1</track_num>
                                <name>The Getaway</name>
                                <length>4:10</length>
                            </song>

                            <song rating="5">
                                <track_num>2</track_num>
                                <name>Dark Necessities</name>
                                <length>5:02</length>
                            </song>

                            <song rating="3">
                                <track_num>7</track_num>
                                <name>Go Robot</name>
                                <length>4:24</length>
                            </song>

                            <song rating="3">
                                <track_num>9</track_num>
                                <name>Detroit</name>
                                <length>3:47</length>
                            </song>

                            <song rating="4">
                                <track_num>13</track_num>
                                <name>Dreams of a Samurai</name>
                                <length>6:09</length>
                            </song>
                        </songs>

                    </album>
                </albums>
            </artist>

            <artist>
                <name>Coldplay</name>
                <career_start>1996</career_start>
                <followers>17 520 663</followers>
                <album_count>1</album_count>
                <albums>
                    <album subgenre_ID="m_2" rating="4">
                        <name>Ghost Stories</name>
                        <release_date>16-11-2014</release_date>
                        <track_count>4</track_count>
                        <songs>
                            <song rating="3">
                                <track_num>1</track_num>
                                <name>Always in My Head</name>
                                <length>3:37</length>
                            </song>

                            <song rating="5">
                                <track_num>2</track_num>
                                <name>Magic</name>
                                <length>4:45</length>
                            </song>

                            <song rating="3">
                                <track_num>7</track_num>
                                <name>Oceans</name>
                                <length>5:22</length>
                            </song>

                            <song rating="5">
                                <track_num>8</track_num>
                                <name>A Sky Full of Stars</name>
                                <length>4:28</length>
                            </song>
                        </songs>
                    </album>
                </albums>
            </artist>

            <artist>
                <name>Mamamoo</name>
                <career_start>2014</career_start>
                <followers>12 580 653</followers>
                <album_count>1</album_count>
                <albums>
                    <album subgenre_ID="m_3" rating="4">
                        <name>Memory</name>
                        <release_date>7-11-2016</release_date>
                        <track_count>7</track_count>
                        <songs>
                            <song rating="3">
                                <track_num>1</track_num>
                                <name>Memory</name>
                                <length>3:52</length>
                            </song>

                            <song rating="5">
                                <track_num>2</track_num>
                                <name>DÃ©calcomanie</name>
                                <length>3:36</length>
                            </song>

                            <song rating="4">
                                <track_num>3</track_num>
                                <name>NEW YORK</name>
                                <length>3:02</length>
                            </song>

                            <song rating="4">
                                <track_num>4</track_num>
